#Maintainer: Rohan B
version: '2.0'

services:
  db-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    volumes:
      - 'db_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=ase
      - POSTGRESQL_PASSWORD=ase
      - POSTGRESQL_DATABASE=ase
  db-slave:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    volumes:
      - 'db_slave_data:/bitnami/postgresql'
    depends_on:
      - db-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=db-master
      - POSTGRESQL_PASSWORD=ase
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  backend:
    build: .
    restart: always
    command: sh -c "python manage.py migrate && gunicorn yaatra.wsgi:application -w 2 -b 0.0.0.0:8000"
    volumes:
      - .:/yaatra
    expose:
      - "8000"
    depends_on:
      - db-master
      - db-slave
  backend-admin:
    build: .
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9595"
    volumes:
      - .:/yaatra
    ports:
      - "9595:9595"
    depends_on:
      - db-master
      - db-slave
  nginx:
    build: ./nginx
    container_name: load-balancer
    depends_on:
      - backend
    ports:
      - "4000:4000"
volumes:
  db_master_data:
  db_slave_data:
